export const TOGGLE_GAME = 'TOGGLE_GAME';
export const PLACE_SYMBOL = 'PLACE_SYMBOL';
export const CHANGE_PLAYER_TURN = 'CHANGE_PLAYER_TURN';
export const SET_PLAYER_ONE = "SET_PLAYER_ONE"
export const SET_PLAYER_TWO = "SET_PLAYER_TWO"
export const TOGGLE_AI = "TOGGLE_AI"